project:
  type: website
  output-dir: docs

website:
  title: "Elena Tuzhilina"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: resume.qmd
        text: Curriculum Vitae
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: talks.qmd
        text: Talks
      - href: teaching.qmd
        text: Teaching
      - href: students.qmd
        text: Students

format:
  html:
    theme: cosmo
    css: styles.css
